# ============================================================
# Endurance Coaching System — new machine setup (PowerShell)
# ============================================================
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

function Say  ($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Warn ($m) { Write-Host "!! $m"  -ForegroundColor Yellow }
function Die  ($m) { Write-Host "XX $m"  -ForegroundColor Red; exit 1 }

$RepoRoot  = (Resolve-Path "$PSScriptRoot\..").Path
$SkillDir  = Join-Path $env:USERPROFILE ".claude\skills\coach"
$CoachDir  = Join-Path $env:USERPROFILE ".endurance-coach"
$ConfigJson = Join-Path $CoachDir "config.json"
$EnvFile   = Join-Path $RepoRoot ".env"

# ---------- prerequisites ----------
Say "Checking prerequisites"
if (-not (Get-Command curl   -ErrorAction SilentlyContinue)) { Die "curl not found" }
$python = (Get-Command python -ErrorAction SilentlyContinue) ?? (Get-Command python3 -ErrorAction SilentlyContinue)
if (-not $python) { Die "python not found" }
Write-Host ("  python: " + (& $python.Source --version))

# ---------- coach skill ----------
Say "Installing Claude Code skill -> $SkillDir"
New-Item -ItemType Directory -Force -Path $SkillDir | Out-Null
Copy-Item "$RepoRoot\claude-skills\coach\SKILL.md" -Destination "$SkillDir\SKILL.md" -Force

# ---------- athlete config ----------
Say "Installing athlete config -> $CoachDir"
New-Item -ItemType Directory -Force -Path $CoachDir | Out-Null
foreach ($f in @('Athlete_Context.md', 'coaching_frameworks.md')) {
    Copy-Item "$RepoRoot\athlete-config\$f" -Destination "$CoachDir\$f" -Force
}
if (Test-Path "$RepoRoot\athlete-config\workout-templates") {
    Copy-Item "$RepoRoot\athlete-config\workout-templates" -Destination $CoachDir -Recurse -Force
}

# ---------- credentials ----------
Say "Configuring intervals.icu credentials"
$reuse = 'N'
$existingId = ''; $existingKey = ''
if (Test-Path $ConfigJson) {
    try {
        $cfg = Get-Content $ConfigJson -Raw | ConvertFrom-Json
        $existingId  = $cfg.intervals.athlete_id
        $existingKey = $cfg.intervals.api_key
        Write-Host ("  Existing config (athlete=$existingId, key=$($existingKey.Substring(0,[Math]::Min(6,$existingKey.Length)))...).")
        $reuse = Read-Host "  Reuse existing? [Y/n]"
        if (-not $reuse) { $reuse = 'Y' }
    } catch { $reuse = 'N' }
}

if ($reuse -match '^[Yy]') {
    $athleteId = $existingId
    $apiKey    = $existingKey
} else {
    $athleteId = Read-Host "  intervals.icu athlete ID (e.g. i12345)"
    $secure    = Read-Host "  intervals.icu API key" -AsSecureString
    $apiKey    = [System.Net.NetworkCredential]::new('', $secure).Password
}
if (-not $athleteId) { Die "athlete_id required" }
if (-not $apiKey)    { Die "api_key required" }

# write config.json
@{
    intervals = @{ athlete_id = $athleteId; api_key = $apiKey }
    sync_days = 730
} | ConvertTo-Json -Depth 4 | Set-Content -Path $ConfigJson -Encoding UTF8
Write-Host "  wrote $ConfigJson"

# write .env
@"
# Auto-generated by install/setup.ps1 -- gitignored, do not commit
INTERVALS_ATHLETE_ID=$athleteId
INTERVALS_API_KEY=$apiKey
"@ | Set-Content -Path $EnvFile -Encoding UTF8
Write-Host "  wrote $EnvFile"

# ---------- verify ----------
Say "Verifying intervals.icu connectivity"
$today  = (Get-Date).ToString('yyyy-MM-dd')
$weekAgo = (Get-Date).AddDays(-7).ToString('yyyy-MM-dd')
$url    = "https://intervals.icu/api/v1/athlete/$athleteId/wellness?oldest=$weekAgo&newest=$today"
$http   = & curl -s -o NUL -w "%{http_code}" -u "API_KEY:$apiKey" $url
if ($http -eq '200') {
    Write-Host "  OK -- API responded 200"
} else {
    Warn "API returned HTTP $http"
}

# ---------- initialize db ----------
Say "Initializing local SQLite database"
& $python.Source "$RepoRoot\scripts\sync_db.py" --init

Say "Done."
Write-Host @"

Next steps:
  1. python scripts/sync_db.py --days 90
  2. python scripts/tsb_check.py --weekly
  3. Open Claude Code; ask a training question -- coach skill auto-activates.

Files installed:
  $SkillDir\SKILL.md
  $CoachDir\Athlete_Context.md
  $CoachDir\coaching_frameworks.md
  $CoachDir\workout-templates\
  $ConfigJson  (private, never committed)
  $EnvFile     (private, never committed)
"@
