#!/usr/bin/env bash
# ============================================================
# Endurance Coaching System — new machine setup
# Works on: Windows Git Bash, macOS, Linux
# ============================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_DIR="${HOME}/.claude/skills/coach"
COACH_DIR="${HOME}/.endurance-coach"

say() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m!! %s\033[0m\n' "$*" >&2; }
die() { printf '\033[1;31mXX %s\033[0m\n' "$*" >&2; exit 1; }

# ---------- prerequisites ----------
say "Checking prerequisites"
command -v curl   >/dev/null || die "curl not found"
command -v python >/dev/null || command -v python3 >/dev/null || die "python not found"
PY=$(command -v python3 || command -v python)
echo "  python: $($PY --version)"
echo "  curl:   $(curl --version | head -1)"

# ---------- coach skill ----------
say "Installing Claude Code skill → ${SKILL_DIR}"
mkdir -p "$SKILL_DIR"
cp "${REPO_ROOT}/claude-skills/coach/SKILL.md" "${SKILL_DIR}/SKILL.md"
echo "  ${SKILL_DIR}/SKILL.md"

# ---------- athlete config ----------
say "Installing athlete config → ${COACH_DIR}"
mkdir -p "$COACH_DIR"
for f in Athlete_Context.md coaching_frameworks.md; do
    cp "${REPO_ROOT}/athlete-config/$f" "${COACH_DIR}/$f"
    echo "  ${COACH_DIR}/$f"
done
if [ -d "${REPO_ROOT}/athlete-config/workout-templates" ]; then
    cp -r "${REPO_ROOT}/athlete-config/workout-templates" "${COACH_DIR}/"
    echo "  ${COACH_DIR}/workout-templates/"
fi

# ---------- credentials ----------
say "Configuring intervals.icu credentials"
CONFIG_JSON="${COACH_DIR}/config.json"
ENV_FILE="${REPO_ROOT}/.env"

read_existing() {
    if [ -f "$CONFIG_JSON" ]; then
        $PY -c "import json; c=json.load(open(r'$CONFIG_JSON')); print(c.get('intervals',{}).get('athlete_id',''),c.get('intervals',{}).get('api_key',''))" 2>/dev/null || true
    fi
}

EXISTING=$(read_existing)
if [ -n "$EXISTING" ]; then
    EX_ATHLETE=$(echo "$EXISTING" | awk '{print $1}')
    EX_KEY=$(echo "$EXISTING" | awk '{print $2}')
    echo "  Existing config detected (athlete=$EX_ATHLETE, key=${EX_KEY:0:6}...)."
    read -rp "  Reuse existing? [Y/n]: " reuse
    reuse="${reuse:-Y}"
else
    reuse="N"
fi

if [[ "$reuse" =~ ^[Yy] ]]; then
    ATHLETE_ID="$EX_ATHLETE"
    API_KEY="$EX_KEY"
else
    read -rp "  intervals.icu athlete ID (e.g. i12345): " ATHLETE_ID
    read -rsp "  intervals.icu API key (input hidden): " API_KEY
    echo
fi
[ -z "$ATHLETE_ID" ] && die "athlete_id required"
[ -z "$API_KEY" ]    && die "api_key required"

# write config.json (gitignored, in $HOME)
cat > "$CONFIG_JSON" <<EOF
{
  "intervals": {
    "athlete_id": "${ATHLETE_ID}",
    "api_key":    "${API_KEY}"
  },
  "sync_days": 730
}
EOF
chmod 600 "$CONFIG_JSON" 2>/dev/null || true
echo "  wrote ${CONFIG_JSON} (chmod 600)"

# write .env (gitignored, at repo root) for scripts
cat > "$ENV_FILE" <<EOF
# Auto-generated by install/setup.sh — gitignored, do not commit
INTERVALS_ATHLETE_ID=${ATHLETE_ID}
INTERVALS_API_KEY=${API_KEY}
EOF
chmod 600 "$ENV_FILE" 2>/dev/null || true
echo "  wrote ${ENV_FILE} (chmod 600)"

# ---------- verify ----------
say "Verifying intervals.icu connectivity"
HTTP=$(curl -s -o /dev/null -w "%{http_code}" -u "API_KEY:${API_KEY}" \
    "https://intervals.icu/api/v1/athlete/${ATHLETE_ID}/wellness?oldest=$(date -d '-7 days' +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d)&newest=$(date +%Y-%m-%d)" || echo "000")
if [ "$HTTP" = "200" ]; then
    echo "  OK — API responded 200"
else
    warn "API returned HTTP $HTTP — credentials may be wrong"
fi

# ---------- initialize db ----------
say "Initializing local SQLite database"
$PY "${REPO_ROOT}/scripts/sync_db.py" --init
echo "  ${COACH_DIR}/coach.db"

# ---------- next steps ----------
say "Done."
cat <<EOF

Next steps:
  1. Run a first sync:
       python scripts/sync_db.py --days 90

  2. Verify TSB:
       python scripts/tsb_check.py --weekly

  3. Open Claude Code and ask a training question — the coach skill
     will activate automatically.

!! IMPORTANT for Strava users !!
  If your activities are synced FROM Strava TO intervals.icu, the intervals.icu
  API only returns 5 basic fields (no distance, no duration, no power streams).
  This breaks TSS / TSB / CTL calculations.

  Fix: Set up Strava direct sync — see SETUP.md §3.5 or docs/getting-credentials.md §3
  Quick check after sync:
       sqlite3 ~/.endurance-coach/coach.db \\
         "SELECT name, distance, moving_time, source FROM activities ORDER BY start_date DESC LIMIT 5;"
  If you see source=STRAVA with distance=0 → you need Strava direct sync.

Files installed:
  ~/.claude/skills/coach/SKILL.md
  ~/.endurance-coach/Athlete_Context.md
  ~/.endurance-coach/coaching_frameworks.md
  ~/.endurance-coach/workout-templates/
  ~/.endurance-coach/config.json   (private, never committed)
  ${REPO_ROOT}/.env                 (private, never committed)

EOF
